stages:
  - build
  - test
  - sonarqube-check
  - docker_build
  - deploy


image: gradle:8.2.0-jdk17-jammy
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  IMAGE_NAME: "first-docker"
  DOCKER_DRIVER: overlay2
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html/
    expire_in: 1 week
  coverage: '/TOTAL.*?([0-9]{1,3})%/'



docker_build:
  stage: docker_build
  script:
    - docker build -t ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA} .

deploy:
  stage: deploy
  dependencies:
    - build
    - docker_build
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}
    - kubectl set image deployment/my-springboot-app my-springboot-app=${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}}


sonarqube-check:
  stage: sonarqube-check
  script:
    - ./gradlew build
    - ./gradlew sonar --info
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'Development'
    - if: $CI_COMMIT_BRANCH == "testing"
