package fontys_s3_eb.stock_project_individual.bussines.PortfolioUseCases.UseCase;

import fontys_s3_eb.stock_project_individual.domain.PortfolioPackage.AddStockToPortfolioRequest;
import fontys_s3_eb.stock_project_individual.domain.PortfolioPackage.AddStockToPortfolioResponse;

public interface AddStockToPortoflioUseCase {
    AddStockToPortfolioResponse addStockToPortfolioResponse (AddStockToPortfolioRequest addStockToPortfolioRequest);
}
